version: '3.4'
services:
  tomato-demo:
      build: .
      ports:
          - "9000:9000"
      env_file:
          - .env
      depends_on:
          - "postgres"
          - "rabbitmq"
          
  postgres:
      image: postgres:9.6
      ports:
          - "5432:5432"
      environment:
          POSTGRES_USER: tomato
          POSTGRES_PASSWORD: potato
      volumes:
        - ./migrations:/docker-entrypoint-initdb.d/

  rabbitmq:
    image: rabbitmq:3.6.1-management
    ports:
        - "15672:15672"
        - "5672:5672"