version: '3.4'
services:
  tomato-demo:
      build: .
      ports:
          - "9000:9000"
      env_file:
          - .env
          
  postgres:
      image: postgres:9.6
      ports:
          - "5432:5432"
      environment:
          POSTGRES_USER: tomato
          POSTGRES_PASSWORD: potato
      volumes:
        - ./migrations:/docker-entrypoint-initdb.d/