version: '3.4'
services:
  tomato:
    image: quay.io/tomatool/tomato:v1.4.2
    volumes:
        - ./features:/features
        - ./tomato.yaml:/config.yml
    depends_on:
      - postgres
      - tomato-demo
      - user-service

  tomato-demo:
      build: ..
      expose:
          - "9000"
      env_file:
          - .env
      depends_on:
        - postgres
        - user-service
          
  postgres:
      image: postgres:9.6
      expose:
          - "5432"
      environment:
          POSTGRES_USER: tomato
          POSTGRES_PASSWORD: potato

  user-service:
      image: rodolpheche/wiremock:2.31.0-alpine
      expose:
          - "8080"